// Eagerly scan and compile all covers and member images from src/assets during compilation
const covers = import.meta.glob("../assets/covers/**/*.{webp,png,jpg,jpeg}", {
  eager: true,
  import: "default",
});

const members = import.meta.glob("../assets/members/**/*.{webp,png,jpg,jpeg}", {
  eager: true,
  import: "default",
});

/**
 * Utility to dynamically resolve assets from src/assets in a Vite environment.
 * Maps string paths (e.g. /covers/albums/vessel.webp) to their corresponding
 * compiled, hashed, and optimized asset path generated by Vite.
 */
export function getAssetUrl(path) {
  if (!path) return "";

  // If path is already an external URL, base64 data, or a resolved asset string, return it directly
  if (
    path.startsWith("http") ||
    path.startsWith("data:") ||
    path.startsWith("blob:") ||
    path.startsWith("/src/assets/") ||
    path.startsWith("/assets/")
  ) {
    return path;
  }

  // Remove leading slash for key mapping
  const cleanPath = path.startsWith("/") ? path.substring(1) : path;

  // Map to the glob key (e.g. "../assets/covers/albums/vessel.webp")
  const assetKey = "../assets/" + cleanPath;

  if (cleanPath.startsWith("covers/")) {
    return covers[assetKey] || path;
  }

  if (cleanPath.startsWith("members/")) {
    return members[assetKey] || path;
  }

  return path;
}
